nav:
  - 'Macrolab': macrolab
  - 'Data aquisition': data-aquisition
  - 'Control systems': control-systems
  - 'Sensors and transducers': sensors-and-transducers
  - 'Electronics': electronics
  - 'Hydraulics': hydraulics