nav:
  - Macrolab:
    - Home: macrolab/index.md
    - General conventions: macrolab/general-conventions.md
    - Testing Machines: macrolab/testing-machines
    - Standard pinouts: macrolab/standard-pinouts.md
    - '3D Printing': macrolab/3d-printing
    - DIC: macrolab/dic
    - EU Standards and Regulations: macrolab/eu-standards-and-regulations
  - 'Data aquisition': data-aquisition
  - 'Control systems': control-systems
  - 'Sensors and transducers': sensors-and-transducers
  - 'Electronics': electronics
  - 'Hydraulics': hydraulics