name: Deploy MkDocs site via SFTP
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  generate:
    name: "Generate static website"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-awesome-nav

      - run: mkdocs gh-deploy --force

  upload:
    name: "Upload generated site via SFTP"
    needs: generate
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: gh-pages

    - name: Deploy files via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: ${{ secrets.FTP_HOST }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        settings: 'sftp:auto-confirm=yes'
        # Mirror command options
        localDir: '.'
        remoteDir: '.'
        reverse: true
        ignoreFile: '.lftp_ignore'
        options: '--verbose'
